[package]
name = "aoc_macro"
version = "1.0.1"
authors = ["Joakim Hulthe <joakim@hulthe.net>"]
edition = "2021"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
regex = "1"
syn = "1"

